### ISSUE TITLE
Prefer VMs over containers in Travis

### ISSUE THREAD

**Issue by ignasi35** [lightbend/templatecontrol#76]
https://changelog.travis-ci.com/the-container-based-build-environment-is-fully-deprecated-84517

**Comment by dwijnand** [comment]
Not necessary, but it makes sense to mass-resolve this via with templatecontrol.

**Comment by dwijnand** [comment]
Already done!  The .travis.yml Marcos added doesn't use sudo: https://github.com/lightbend/templatecontrol/commit/fa12d9afd0565eb0a6187cbf089baa8185496eb6#diff-1b73ee3d35c55099866134b4ab3115ea.
